/**
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.brixcms.markup;

import org.apache.wicket.Component;
import org.apache.wicket.MarkupContainer;
import org.brixcms.jcr.wrapper.BrixNode;
import org.brixcms.markup.tag.ComponentTag;
import org.brixcms.markup.tag.Tag;
import org.brixcms.plugin.site.SitePlugin;
import org.brixcms.web.generic.IGenericComponent;

import java.io.Serializable;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HashSet;
import java.util.HexFormat;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;

/**
 * Helper class for components with custom node markup. This class takes care of generating the markup and
 * creating/removing of appropriate wicket components.
 *
 * @author Matej Knopp
 */
public class MarkupHelper implements Serializable {
    /**
     * Each tag component ids prefixed by this.
     */
    private final static String COMPONENT_PREFIX = "brix-";

    private final IGenericComponent<BrixNode> component;

    private final String markup;

    private final String markupHash;

    private final String workspace;

    private final String nodeId;

    public MarkupHelper(IGenericComponent<BrixNode> component) {
        this.component = component;
        GeneratedMarkup generatedMarkup = getMarkupCache().getMarkup(component);
        this.workspace = generatedMarkup.workspace;
        this.nodeId = generatedMarkup.nodeId;
        this.markup = initMarkup(generatedMarkup);
        this.markupHash = sha256(markup);
    }

    /**
     * Generates the markup and makes sure that the markup container contains all components generated by the {@link
     * ComponentTag}s in markup. Also removes components no longer present in markup.
     */
    private String initMarkup(GeneratedMarkup markup) {
        final Set<String> components = new HashSet<String>();
        final Set<String> existingComponents = getExistingComponents();

        MarkupRenderer renderer = new MarkupRenderer(markup.items, markup.doctype) {
            @Override
            void postprocessTagAttributes(Tag tag, Map<String, String> attributes) {
                // if during rendering we have a ComponentTag
                if (tag instanceof ComponentTag componentTag && tag.getType() != Tag.Type.CLOSE) {
                    String id = getComponentID(componentTag);

                    // check if the component already is in hierarchy
                    if (existingComponents.contains(id)) {
                        // just put the wicket:id attribute to component tag
                        attributes.put("wicket:id", id);
                        components.add(id);
                    } else {
                        // otherwise we need to create the component instance
                        Component c = componentTag.getComponent(id, component.getModel());
                        if (c != null) {
                            attributes.put("wicket:id", id);
                            components.add(id);
                            ((MarkupContainer) component).add(c);
                            existingComponents.add(id);
                        }
                    }
                }
            }
        };
        String renderedMarkup = renderer.render();

        // go through existing components and remove those not present in
        // current markup
        for (String s : existingComponents) {
            if (!components.contains(s)) {
                ((MarkupContainer) component).get(s).remove();
            }
        }
        return renderedMarkup;
    }

    /**
     * Returns existing tag components on page.
     *
     * @return
     */
    private Set<String> getExistingComponents() {
        Set<String> result = new HashSet<String>();
        Iterator<? extends Component> i = ((MarkupContainer) component).iterator();
        while (i.hasNext()) {
            Component c = i.next();
            if (c.getId().startsWith(COMPONENT_PREFIX)) {
                result.add(c.getId());
            }
        }
        return result;
    }

    public static String getComponentID(ComponentTag tag) {
        String uid = tag.getUniqueTagId();
        return COMPONENT_PREFIX + (uid != null ? uid.toString() : "");
    }

    public String getMarkup() {
        return markup;
    }

    public String getCacheKey(MarkupContainer container, Class<?> containerClass) {
        String locale = container.getLocale() == null ? null : container.getLocale().toLanguageTag();
        String markupType = container.getMarkupType() == null ? null : container.getMarkupType().getExtension();
        return getMarkupCache().getWicketCacheKey(workspace, nodeId, containerClass.getName(), locale,
                container.getStyle(), container.getVariation(), markupType, markupHash);
    }

    static String sha256(String value) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            return HexFormat.of().formatHex(digest.digest(value.getBytes(StandardCharsets.UTF_8)));
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is not available", e);
        }
    }

    private MarkupCache getMarkupCache() {
        return SitePlugin.get().getMarkupCache();
    }
}
